# ===============================
# = MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/falapraele_users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=bruno
spring.datasource.password=Bruno0665
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration for MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# = MongoDB Database Configuration
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/falapraele

# URI format (alternativa mais comum)
# spring.data.mongodb.uri=mongodb://usuario:senha@localhost:27017/seu_banco